### ISSUE TITLE
Static files not replaced if already existing.

### ISSUE THREAD

**Issue by PXke** [klen/Flask-Collect#13]
Hello, 

We are currently working with Invenio (https://github.com/inveniosoftware/invenio) a CERN, flask based application, that use Flask-Collect. 

Invenio allows to add overlay with new design. Which means that we are collecting, first, static files from core, then from the different setuped overlays. 

Unfortunately because the static files  from the overlays have the same name, they are not replaced.
##

**Comment by jirikuncar** [comment]
@PXke you would need to pass an extra argument (`-f`, `--force`) to `collect` command (https://github.com/klen/Flask-Collect/blob/develop/flask_collect/collect.py#L93-L97).

**Comment by PXke** [comment]
Okay ! I will do that :) !
