### ISSUE TITLE
Click and Flask 1.0

### ISSUE THREAD

**Issue by jirikuncar** [klen/Flask-Collect#15]
- [x] prepare Flask-Collect for upcoming Flask 1.0 (#14)
- [x] create Click command and `init_cli` method
  - For compatibility with Flask<1.0 we can use https://github.com/inveniosoftware/flask-cli
- [x] refactor code so Flask-Script and Flask-Cli can be optional

**Comment by klen** [comment]
Do you know when Flask 1.0 will be released?

**Comment by jirikuncar** [comment]
@klen I don't know, but I'm trying to get our extensions and packages ready. We have released backports of *Flask* and *Click* integration as *Flask-Cli* so we can do something like:

```python
try:
    from flask.cli import FlaskGroup
except ImportError:  # fallback
    from flask_cli import FlaskGroup
```
