### ISSUE TITLE
How to use factory function and Flask Script add_command?

### ISSUE THREAD

**Issue by saschwarz** [klen/Flask-Collect#21]
I setup `Collect` in my `create_app` factory function but I don't have access to the Manager at that time. When I create the `Manager` how do I add the collect command to it?

```
from myapp import create_app

manager = Manager(create_app)
manager.add_command('collect', ????)
```

Thanks.

**Comment by jirikuncar** [comment]
@saschwarz you can following pattern:

``` python

manager = Manager()

def create_app():
    app = Flask(__name__)
    manager.init_app(app)
    return app
```

or simply use Flask 0.11 and take advantage of Click integration. 

``` console
$ export FLASK_APP="myapp.app"
$ flask collect
```

**Comment by saschwarz** [comment]
Thanks for the reply and making me aware of Click integration. I'll to get rid of my `manage.py` and convert my commands to work with Flask 0.11 Click integration.
